# Generated by Django 4.0.2 on 2022-07-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_achievement_batch_expense_machine_workout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateField(blank=True, null=True)),
                ('todate', models.DateField(blank=True, null=True)),
                ('fromtime', models.TimeField(blank=True, null=True)),
                ('totime', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='', max_length=240, null=True)),
            ],
        ),
    ]
