# Generated by Django 4.0.2 on 2022-07-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.CharField(default='', max_length=240, null=True),
        ),
    ]
