# Generated by Django 4.0.2 on 2022-07-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='work_shift',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
