# Generated by Django 4.0.2 on 2022-07-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_registration_work_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Bookingtrainer', to='app.user_registration'),
        ),
        migrations.AddField(
            model_name='booking',
            name='work_shift',
            field=models.CharField(default='', max_length=240, null=True),
        ),
    ]
